Given /^the API pages have been generated by Yard version 0\.5$/ do
  pending # express the regexp above with the code you wish you had
end

Given /^the API pages are published$/ do
  pending # express the regexp above with the code you wish you had
end

Then /^I should see "([^\"]*)" table$/ do |arg1, table|
  # table is a Cucumber::Ast::Table
  pending # express the regexp above with the code you wish you had
end
